stages:
  preprocess:
    cmd: python src/data_process.py
    deps:
      - src/data_process.py
      - data/train.csv
    outs:
      - data/processed/train_processed.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train_processed.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/eval.py
    deps:
      - src/eval.py
      - models/model.pkl
